Разработка основного функционала бота
ArturSpe/TelegramBot pull request #2
Opened 2022-09-06 12:56 UTC by ArturSpe

2022-09-06 13:21 UTC, aimalygin requested changes

2022-09-06 13:21 UTC, aimalygin commented on BotWithPengrad/src/main/java/Main.java
> +                        if (userState.emptyUserState(userId) == true && update.message().text() != null){
Чтобы не писать тут и выше несколько раз одно и тоже update.message().text(), можно сделать это один раз в твоем объекте UserMetaData, предварительно его переименовав

2022-09-06 13:21 UTC, aimalygin commented on BotWithPengrad/src/main/java/WorkWithSql/workingWithJdbc.java
>  public class workingWithJdbc implements dataBaseCommands {
Тут с больших букв

2022-09-06 13:21 UTC, aimalygin commented on BotWithPengrad/src/main/java/WorkWithSql/workingWithJdbc.java
> +        String toLowerSentence = sentence.toLowerCase().replaceAll("[^\\p{L}\\s]+", "");
Если у тебя класс отвечает за jdbc, мне кажется лучше ему уже готовые данные передавать, т.е. эту логику лучше вынести куда-то, и здесь будет выполнятся только сам запрос к бд

2022-09-06 18:28 UTC, neoxack commented on BotWithPengrad/src/main/java/BotRunner.java
> +        UserState userState = new UserState();
лучше в конструктор перенеси и используй как поля класса.

2022-09-06 18:28 UTC, neoxack commented on BotWithPengrad/src/main/java/WorkWithSql/DataBaseRunBot.java
> +public interface DataBaseRunBot {
интерфейсы с буквы I должны по идее называться

2022-09-06 18:28 UTC, neoxack commented on BotWithPengrad/src/main/java/WorkWithSql/DataBaseRunBot.java
> +
Возвращай не сырые строки, а экземпляры классов, внутри которых будет токен бота и адрес базы

2022-09-06 18:28 UTC, neoxack commented on BotWithPengrad/src/main/java/WorkWithSql/WorkingWithJdbc.java
> +public class workingWithJdbc implements dataBaseCommands {
названия классов с большой буквы

2022-09-06 18:55 UTC, aimalygin requested changes

2022-09-06 18:55 UTC, aimalygin commented on BotWithPengrad/src/main/java/BotRunner.java
> +                        if (update.message().text().equals("1")) {
Почему так и осталось?

2022-09-06 18:55 UTC, aimalygin commented on BotWithPengrad/src/main/java/BotRunner.java
> +                        if (update.message().text().equals("2") && userState.emptyUserState(userId)) {
Тут тоже. Всю инфу, нужную тебе в Update, собери в свой класс UserData

2022-09-08 18:20 UTC, neoxack commented on BotWithPengrad/src/main/java/BotRunner.java
> +    private String DB_URL;
Зачем оставил эти перемнные, если не юзаешь их

2022-09-08 18:24 UTC, neoxack commented on BotWithPengrad/src/main/java/BotRunner.java
> +    UserState userState;
private

2022-09-08 18:28 UTC, neoxack commented on BotWithPengrad/src/main/java/WorkWithSql/WorkingWithJdbc.java
> +    @Override
зачем override?

2022-09-11 18:17 UTC, merged